project_id = "lrvkdvjkukxderubuzpr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:54324"
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_confirmations = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.satellite-data-fetcher]
verify_jwt = true

[functions.start-monitoring]
verify_jwt = true

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[analytics]
enabled = false

[inbound_smtp]
enabled = false

[studio]
enabled = true
port = 54323

[edge-runtime]
enabled = true
port = 54325
policy = "oneshot"
inspector_port = 8083